### PR TITLE
Setup React, Vite, Typescript

### LINKED ISSUE #13: [New Feature]: Add React
### What are you requesting?

We should add react (maybe using Typescript & Vite) to the `Web` folder

### What platforms will work be required for?

Web

### PR DESCRIPTION
**Pull request by JackMoseley2001**
Resolves #13 

### Checklist ✅

- [x] Have you checked to see whether there are any conflicting / similar PRs already open?
- [ ] ~Does your PR add any new tests~
- [ ] ~Does your PR pass all existing & new tests~
- [ ] ~Does your PR pass the linter?~

### What does this PR do? 🤔

Adds the basic template for React, Vite and Typescript 🎉 

Please add your thoughts on using Vite & Typescript!

### CODE REVIEW

**Comment by JavaRip** [comment]
looks fab ty

**Comment by TravioliGit** [comment]
bangin'

**Review by zinebibnou — APPROVED** [review]
👌

**Comment by S4-K1** [comment]
Nice work bb 😘

**Comment by mark-chit** [comment]
damn 😍

**Comment by arorh** [comment]
looks good

**Comment by Beamedy** [comment]
looks great

**Pull request merged**
